import logging
import threading
import datetime
from typing import Dict, Any

from shared_core.memory_engine.manager import MemoryManager
from shared_core.memory_engine.kg_query import KGQueryService
from shared_core.memory_engine.entity_types import EntityType

log = logging.getLogger(__name__)

LEARNED_PREFERENCE_CATEGORY = "learned_preference"

class PreferenceLearningJob:
    """
    Phase C10: Evaluates semantic habits (generated by C9) to infer 
    broad profile constraints and preferences (e.g. prefers tools, prefers workflows)
    and stores them strictly in the relational `profile_entries` table under 
    'learned_preference' and 'learned_profile'.
    """
    def __init__(self, memory_manager: MemoryManager, kg_query_service: KGQueryService):
        self.memory = memory_manager
        self.kg_query = kg_query_service
        self._lock = threading.Lock()

    def run_once(self, now: str | None = None) -> Dict[str, Any]:
        """
        Executes a single sweep over Habit entities.
        """
        if not self._lock.acquire(blocking=False):
            return {"status": "already_running"}

        try:
            habits = self.memory.get_entities_by_type(EntityType.HABIT, limit=5000)
            
            inferred_count = 0
            scanned_habits = len(habits)

            for habit_id in habits:
                # We extract pattern attributes 
                triples = self.memory.query_triples(subject=habit_id)
                action = None
                target = None
                outcome = None
                actor = None
                for t in triples:
                    if t["predicate"] == "pattern_action":
                        action = t["object"]
                    elif t["predicate"] == "pattern_target":
                        target = t["object"]
                    elif t["predicate"] == "pattern_outcome":
                        outcome = t["object"]
                    elif t["predicate"] == "pattern_actor":
                        actor = t["object"]

                if action and target:
                    clean_action = str(action).replace("literal:action:", "")
                    clean_target = str(target)
                    
                    # Deduplicate/normalize a preference key
                    import hashlib
                    # Make a clean predictable key from habit core
                    sig = f"{clean_action}_{clean_target}".encode("utf-8")
                    key_hash = hashlib.sha256(sig).hexdigest()[:12]
                    key = f"habit_{clean_action}_{key_hash}"
                    
                    value = f"User habitually performs {clean_action} on {clean_target} (Inferred from behavioral provenance {habit_id})"
                    
                    
                    self.memory.save_profile_detail(
                        category=LEARNED_PREFERENCE_CATEGORY,
                        key=key,
                        value=value,
                        label=f"Learned preference for {clean_action}"
                    )
                    inferred_count += 1
            
            return {
                "status": "success",
                "scanned_habits": scanned_habits,
                "inferred_preferences": inferred_count
            }
        except Exception as e:
            log.exception(f"PreferenceLearningJob failed: {e}")
            return {"status": "error", "error": str(e)}
        finally:
            self._lock.release()
